# Generated by Django 4.1.7 on 2023-04-05 12:24

from django.db import migrations, models
import fastfood_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', fastfood_auth.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
